name: Verify library

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        pip install -U pip setuptools
        pip install -r requirements.txt

    - run: oj-verify run